/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-338
 *
 */
import { FluencePeer } from '@fluencelabs/fluence';
export declare type Get_external_swarm_multiaddrResult = {
    error: string;
    multiaddr: string;
    success: boolean;
};
export declare function get_external_swarm_multiaddr(node: string, config?: {
    ttl?: number;
}): Promise<Get_external_swarm_multiaddrResult>;
export declare function get_external_swarm_multiaddr(peer: FluencePeer, node: string, config?: {
    ttl?: number;
}): Promise<Get_external_swarm_multiaddrResult>;
export declare function set_timeout(node: string, timeout_sec: number, config?: {
    ttl?: number;
}): Promise<void>;
export declare function set_timeout(peer: FluencePeer, node: string, timeout_sec: number, config?: {
    ttl?: number;
}): Promise<void>;
export declare type Get_external_api_multiaddrResult = {
    error: string;
    multiaddr: string;
    success: boolean;
};
export declare function get_external_api_multiaddr(node: string, config?: {
    ttl?: number;
}): Promise<Get_external_api_multiaddrResult>;
export declare function get_external_api_multiaddr(peer: FluencePeer, node: string, config?: {
    ttl?: number;
}): Promise<Get_external_api_multiaddrResult>;
