[package]
name = "media-service"
version = "0.1.0"
authors = ["ssd39 <saurabh.sachit39@gmail.com>"]
edition = "2018"

[[bin]]
name = "media_service"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.6.15"
image = "0.24.3"

[dev-dependencies]
marine-rs-sdk-test = "0.5.0"
